name: tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  actions: write
  contents: read

jobs:
  benders:
    name: PlasmoBenders
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.10']
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v1
      - name: Run tests (PlasmoBenders)
        env:
          PKG: PlasmoBenders
        run: julia --color=yes .ci/ci.jl

  schwarz:
    name: PlasmoSchwarz
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.10']
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v1
      - name: Run tests (PlasmoSchwarz)
        env:
          PKG: PlasmoSchwarz
        run: julia --color=yes .ci/ci.jl
